package top.fifthlight.renderer.model

// Generated by AI, not checked manually.
enum class HumanoidTag(
    val vrmName: String? = null,
    val pmxEnglish: String? = null,
    val pmxJapanese: String? = null,
) {
    // ===== VRM Standard Bones =====
    // Torso
    HIPS(vrmName = "hips", pmxEnglish = "Pelvis", pmxJapanese = "下半身"),
    SPINE(vrmName = "spine", pmxEnglish = "Spine", pmxJapanese = "上半身"),
    CHEST(vrmName = "chest", pmxEnglish = "Chest", pmxJapanese = "胸"),
    UPPER_CHEST(vrmName = "upperChest", pmxEnglish = "Upper Chest", pmxJapanese = "上半身2"),
    NECK(vrmName = "neck", pmxEnglish = "Neck", pmxJapanese = "首"),

    // Head
    HEAD(vrmName = "head", pmxEnglish = "Head", pmxJapanese = "頭"),
    LEFT_EYE(vrmName = "leftEye", pmxEnglish = "Left Eye", pmxJapanese = "左目"),
    RIGHT_EYE(vrmName = "rightEye", pmxEnglish = "Right Eye", pmxJapanese = "右目"),
    JAW(vrmName = "jaw", pmxEnglish = "Jaw", pmxJapanese = "あご"),

    // Leg
    LEFT_UPPER_LEG(vrmName = "leftUpperLeg", pmxEnglish = "Left Leg", pmxJapanese = "左足"),
    LEFT_LOWER_LEG(vrmName = "leftLowerLeg", pmxEnglish = "Left Knee", pmxJapanese = "左ひざ"),
    LEFT_FOOT(vrmName = "leftFoot", pmxEnglish = "Left Ankle", pmxJapanese = "左足首"),
    LEFT_TOES(vrmName = "leftToes", pmxEnglish = "Left Toe", pmxJapanese = "左つま先"),
    RIGHT_UPPER_LEG(vrmName = "rightUpperLeg", pmxEnglish = "Right Leg", pmxJapanese = "右足"),
    RIGHT_LOWER_LEG(vrmName = "rightLowerLeg", pmxEnglish = "Right Knee", pmxJapanese = "右ひざ"),
    RIGHT_FOOT(vrmName = "rightFoot", pmxEnglish = "Right Ankle", pmxJapanese = "右足首"),
    RIGHT_TOES(vrmName = "rightToes", pmxEnglish = "Right Toe", pmxJapanese = "右つま先"),

    // Arm
    LEFT_SHOULDER(vrmName = "leftShoulder", pmxEnglish = "Left Shoulder", pmxJapanese = "左肩"),
    LEFT_UPPER_ARM(vrmName = "leftUpperArm", pmxEnglish = "Left Arm", pmxJapanese = "左腕"),
    LEFT_LOWER_ARM(vrmName = "leftLowerArm", pmxEnglish = "Left Elbow", pmxJapanese = "左ひじ"),
    LEFT_HAND(vrmName = "leftHand", pmxEnglish = "Left Wrist", pmxJapanese = "左手首"),
    RIGHT_SHOULDER(vrmName = "rightShoulder", pmxEnglish = "Right Shoulder", pmxJapanese = "右肩"),
    RIGHT_UPPER_ARM(vrmName = "rightUpperArm", pmxEnglish = "Right Arm", pmxJapanese = "右腕"),
    RIGHT_LOWER_ARM(vrmName = "rightLowerArm", pmxEnglish = "Right Elbow", pmxJapanese = "右ひじ"),
    RIGHT_HAND(vrmName = "rightHand", pmxEnglish = "Right Wrist", pmxJapanese = "右手首"),

    // Finger
    LEFT_THUMB_METACARPAL(vrmName = "leftThumbMetacarpal", pmxEnglish = "Left Thumb 1", pmxJapanese = "左親指１"),
    LEFT_THUMB_PROXIMAL(vrmName = "leftThumbProximal", pmxEnglish = "Left Thumb 2", pmxJapanese = "左親指２"),
    LEFT_THUMB_DISTAL(vrmName = "leftThumbDistal", pmxEnglish = "Left Thumb 3", pmxJapanese = "左親指３"),
    LEFT_INDEX_PROXIMAL(vrmName = "leftIndexProximal", pmxEnglish = "Left Index 1", pmxJapanese = "左人指１"),
    LEFT_INDEX_INTERMEDIATE(vrmName = "leftIndexIntermediate", pmxEnglish = "Left Index 2", pmxJapanese = "左人指２"),
    LEFT_INDEX_DISTAL(vrmName = "leftIndexDistal", pmxEnglish = "Left Index 3", pmxJapanese = "左人指３"),
    LEFT_MIDDLE_PROXIMAL(vrmName = "leftMiddleProximal", pmxEnglish = "Left Middle 1", pmxJapanese = "左中指１"),
    LEFT_MIDDLE_INTERMEDIATE(vrmName = "leftMiddleIntermediate", pmxEnglish = "Left Middle 2", pmxJapanese = "左中指２"),
    LEFT_MIDDLE_DISTAL(vrmName = "leftMiddleDistal", pmxEnglish = "Left Middle 3", pmxJapanese = "左中指３"),
    LEFT_RING_PROXIMAL(vrmName = "leftRingProximal", pmxEnglish = "Left Ring 1", pmxJapanese = "左薬指１"),
    LEFT_RING_INTERMEDIATE(vrmName = "leftRingIntermediate", pmxEnglish = "Left Ring 2", pmxJapanese = "左薬指２"),
    LEFT_RING_DISTAL(vrmName = "leftRingDistal", pmxEnglish = "Left Ring 3", pmxJapanese = "左薬指３"),
    LEFT_LITTLE_PROXIMAL(vrmName = "leftLittleProximal", pmxEnglish = "Left Little 1", pmxJapanese = "左小指１"),
    LEFT_LITTLE_INTERMEDIATE(vrmName = "leftLittleIntermediate", pmxEnglish = "Left Little 2", pmxJapanese = "左小指２"),
    LEFT_LITTLE_DISTAL(vrmName = "leftLittleDistal", pmxEnglish = "Left Little 3", pmxJapanese = "左小指３"),
    RIGHT_THUMB_METACARPAL(vrmName = "rightThumbMetacarpal", pmxEnglish = "Right Thumb 1", pmxJapanese = "右親指１"),
    RIGHT_THUMB_PROXIMAL(vrmName = "rightThumbProximal", pmxEnglish = "Right Thumb 2", pmxJapanese = "右親指２"),
    RIGHT_THUMB_DISTAL(vrmName = "rightThumbDistal", pmxEnglish = "Right Thumb 3", pmxJapanese = "右親指３"),
    RIGHT_INDEX_PROXIMAL(vrmName = "rightIndexProximal", pmxEnglish = "Right Index 1", pmxJapanese = "右人指１"),
    RIGHT_INDEX_INTERMEDIATE(vrmName = "rightIndexIntermediate", pmxEnglish = "Right Index 2", pmxJapanese = "右人指２"),
    RIGHT_INDEX_DISTAL(vrmName = "rightIndexDistal", pmxEnglish = "Right Index 3", pmxJapanese = "右人指３"),
    RIGHT_MIDDLE_PROXIMAL(vrmName = "rightMiddleProximal", pmxEnglish = "Right Middle 1", pmxJapanese = "右中指１"),
    RIGHT_MIDDLE_INTERMEDIATE(vrmName = "rightMiddleIntermediate", pmxEnglish = "Right Middle 2", pmxJapanese = "右中指２"),
    RIGHT_MIDDLE_DISTAL(vrmName = "rightMiddleDistal", pmxEnglish = "Right Middle 3", pmxJapanese = "右中指３"),
    RIGHT_RING_PROXIMAL(vrmName = "rightRingProximal", pmxEnglish = "Right Ring 1", pmxJapanese = "右薬指１"),
    RIGHT_RING_INTERMEDIATE(vrmName = "rightRingIntermediate", pmxEnglish = "Right Ring 2", pmxJapanese = "右薬指２"),
    RIGHT_RING_DISTAL(vrmName = "rightRingDistal", pmxEnglish = "Right Ring 3", pmxJapanese = "右薬指３"),
    RIGHT_LITTLE_PROXIMAL(vrmName = "rightLittleProximal", pmxEnglish = "Right Little 1", pmxJapanese = "右小指１"),
    RIGHT_LITTLE_INTERMEDIATE(vrmName = "rightLittleIntermediate", pmxEnglish = "Right Little 2", pmxJapanese = "右小指２"),
    RIGHT_LITTLE_DISTAL(vrmName = "rightLittleDistal", pmxEnglish = "Right Little 3", pmxJapanese = "右小指３"),

    // ===== PMX Specific Bones (not in VRM) =====
    // Additional body bones
    WAIST(pmxEnglish = "Waist", pmxJapanese = "腰"),
    BREAST(pmxEnglish = "Breast", pmxJapanese = "胸"),
    SCAPULA(pmxEnglish = "Scapula", pmxJapanese = "肩先"),

    // Face bones
    BROW(pmxEnglish = "Brow", pmxJapanese = "眉"),
    EYE_LID(pmxEnglish = "Eye Lid", pmxJapanese = "まぶた"),
    MOUTH(pmxEnglish = "Mouth", pmxJapanese = "口"),
    TONGUE(pmxEnglish = "Tongue", pmxJapanese = "舌"),

    // Additional arm bones
    ARM_TWIST(pmxEnglish = "Arm Twist", pmxJapanese = "腕捩"),
    WRIST_TWIST(pmxEnglish = "Wrist Twist", pmxJapanese = "手首捩"),

    // Additional leg bones
    LEG_TWIST(pmxEnglish = "Leg Twist", pmxJapanese = "足捩"),
    ANKLE_TWIST(pmxEnglish = "Ankle Twist", pmxJapanese = "足首捩"),

    // Additional finger bones
    FINGER_TIP(pmxEnglish = "Finger Tip", pmxJapanese = "指先"),

    // Special bones
    ROOT(pmxEnglish = "Root", pmxJapanese = "センター"),
    GROOVE(pmxEnglish = "Groove", pmxJapanese = "グルーブ"),
    HAIR(pmxEnglish = "Hair", pmxJapanese = "髪"),
    SKIRT(pmxEnglish = "Skirt", pmxJapanese = "スカート"),
    DRESS(pmxEnglish = "Dress", pmxJapanese = "ドレス"),
    ACCESSORY(pmxEnglish = "Accessory", pmxJapanese = "アクセサリ");

    companion object {
        private val vrmNameMap = entries.associate { Pair(it.vrmName, it) }
        private val pmxEnglishMap = entries.associate { Pair(it.pmxEnglish, it) }
        private val pmxJapaneseMap = entries.associate { Pair(it.pmxJapanese, it) }

        fun fromVrmName(name: String): HumanoidTag? = vrmNameMap[name]
        fun fromPmxEnglish(name: String): HumanoidTag? = pmxEnglishMap[name]
        fun fromPmxJapanese(name: String): HumanoidTag? = pmxJapaneseMap[name]
    }
}
