# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on: [pull_request, push]

jobs:
  build-with-bazel:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - uses: bazel-contrib/setup-bazel@0.14.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
      - name: build
        run: bazel build @//mod @//blazerod @//blazerod/model/model-base @//blazerod/model/model-formats @//blazerod/model/model-gltf @//blazerod/model/model-pmd @//blazerod/model/model-pmx @//blazerod/model/model-vmd @//blazerod/example/ball_block --verbose_failures
      - name: test
        run: bazel test @//blazerod/model/model-gltf:glb_load_test @//blazerod/render:standalone_tests --verbose_failures
      - name: capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-bazel
          path: |
            bazel-bin/mod/mod.jar
            bazel-bin/blazerod/blazerod.jar
            bazel-bin/blazerod/model/model-base/model-base.jar
            bazel-bin/blazerod/model/model-formats/model-formats.jar
            bazel-bin/blazerod/model/model-gltf/model-gltf.jar
            bazel-bin/blazerod/model/model-pmd/model-pmd.jar
            bazel-bin/blazerod/model/model-pmx/model-pmx.jar
            bazel-bin/blazerod/model/model-vmd/model-vmd.jar
            bazel-bin/blazerod/example/ball_block/ball_block.jar
